// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: market_data.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for a risk report
type RiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskRequest) Reset() {
	*x = RiskRequest{}
	mi := &file_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRequest) ProtoMessage() {}

func (x *RiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRequest.ProtoReflect.Descriptor instead.
func (*RiskRequest) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *RiskRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

// Response containing the risk report
type RiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	ReportContent string                 `protobuf:"bytes,2,opt,name=report_content,json=reportContent,proto3" json:"report_content,omitempty"`
	RiskScore     float32                `protobuf:"fixed32,3,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Citations     []string               `protobuf:"bytes,4,rep,name=citations,proto3" json:"citations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
	mi := &file_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskResponse.ProtoReflect.Descriptor instead.
func (*RiskResponse) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *RiskResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *RiskResponse) GetReportContent() string {
	if x != nil {
		return x.ReportContent
	}
	return ""
}

func (x *RiskResponse) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *RiskResponse) GetCitations() []string {
	if x != nil {
		return x.Citations
	}
	return nil
}

// Message for market data (Ticks)
type MarketTick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketTick) Reset() {
	*x = MarketTick{}
	mi := &file_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketTick) ProtoMessage() {}

func (x *MarketTick) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketTick.ProtoReflect.Descriptor instead.
func (*MarketTick) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *MarketTick) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *MarketTick) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MarketTick) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Message for News
type NewsItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ticker        string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Headline      string                 `protobuf:"bytes,3,opt,name=headline,proto3" json:"headline,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsItem) Reset() {
	*x = NewsItem{}
	mi := &file_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsItem) ProtoMessage() {}

func (x *NewsItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsItem.ProtoReflect.Descriptor instead.
func (*NewsItem) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{3}
}

func (x *NewsItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewsItem) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *NewsItem) GetHeadline() string {
	if x != nil {
		return x.Headline
	}
	return ""
}

func (x *NewsItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NewsItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Message for Sentiment Analysis
type SentimentReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewsId         string                 `protobuf:"bytes,1,opt,name=news_id,json=newsId,proto3" json:"news_id,omitempty"`
	Ticker         string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	SentimentScore float32                `protobuf:"fixed32,3,opt,name=sentiment_score,json=sentimentScore,proto3" json:"sentiment_score,omitempty"` // -1.0 to 1.0
	Rationale      string                 `protobuf:"bytes,4,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SentimentReport) Reset() {
	*x = SentimentReport{}
	mi := &file_market_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentimentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentReport) ProtoMessage() {}

func (x *SentimentReport) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentReport.ProtoReflect.Descriptor instead.
func (*SentimentReport) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{4}
}

func (x *SentimentReport) GetNewsId() string {
	if x != nil {
		return x.NewsId
	}
	return ""
}

func (x *SentimentReport) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *SentimentReport) GetSentimentScore() float32 {
	if x != nil {
		return x.SentimentScore
	}
	return 0
}

func (x *SentimentReport) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

var File_market_data_proto protoreflect.FileDescriptor

const file_market_data_proto_rawDesc = "" +
	"\n" +
	"\x11market_data.proto\x12\vmarket_data\"%\n" +
	"\vRiskRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\"\x8a\x01\n" +
	"\fRiskResponse\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12%\n" +
	"\x0ereport_content\x18\x02 \x01(\tR\rreportContent\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x03 \x01(\x02R\triskScore\x12\x1c\n" +
	"\tcitations\x18\x04 \x03(\tR\tcitations\"X\n" +
	"\n" +
	"MarketTick\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x86\x01\n" +
	"\bNewsItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x1a\n" +
	"\bheadline\x18\x03 \x01(\tR\bheadline\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x89\x01\n" +
	"\x0fSentimentReport\x12\x17\n" +
	"\anews_id\x18\x01 \x01(\tR\x06newsId\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12'\n" +
	"\x0fsentiment_score\x18\x03 \x01(\x02R\x0esentimentScore\x12\x1c\n" +
	"\trationale\x18\x04 \x01(\tR\trationale2S\n" +
	"\vRiskService\x12D\n" +
	"\rGetRiskReport\x12\x18.market_data.RiskRequest\x1a\x19.market_data.RiskResponseB8Z6github.com/ng-namanh/rsias/backend/internal/grpc/protob\x06proto3"

var (
	file_market_data_proto_rawDescOnce sync.Once
	file_market_data_proto_rawDescData []byte
)

func file_market_data_proto_rawDescGZIP() []byte {
	file_market_data_proto_rawDescOnce.Do(func() {
		file_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)))
	})
	return file_market_data_proto_rawDescData
}

var file_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_market_data_proto_goTypes = []any{
	(*RiskRequest)(nil),     // 0: market_data.RiskRequest
	(*RiskResponse)(nil),    // 1: market_data.RiskResponse
	(*MarketTick)(nil),      // 2: market_data.MarketTick
	(*NewsItem)(nil),        // 3: market_data.NewsItem
	(*SentimentReport)(nil), // 4: market_data.SentimentReport
}
var file_market_data_proto_depIdxs = []int32{
	0, // 0: market_data.RiskService.GetRiskReport:input_type -> market_data.RiskRequest
	1, // 1: market_data.RiskService.GetRiskReport:output_type -> market_data.RiskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_data_proto_init() }
func file_market_data_proto_init() {
	if File_market_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_data_proto_goTypes,
		DependencyIndexes: file_market_data_proto_depIdxs,
		MessageInfos:      file_market_data_proto_msgTypes,
	}.Build()
	File_market_data_proto = out.File
	file_market_data_proto_goTypes = nil
	file_market_data_proto_depIdxs = nil
}
